#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_ergodox(KC_EQL, KC_1, KC_2, KC_3, KC_4, KC_5, KC_ESC, KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, LT(1,KC_GRV), KC_LCTL, KC_A, KC_S, KC_D, KC_F, KC_G, KC_RALT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_LGUI, KC_NO, KC_NO, KC_NO, KC_LALT, MO(3), KC_PSCR, KC_HOME, KC_END, KC_LSFT, KC_SPC, KC_DEL, KC_NO, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS, KC_NUBS, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSLS, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_RGUI, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RALT, MO(2), KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_PGUP, TG(1), KC_PGDN, KC_INS, KC_ENT, MO(2)),
	[1] = LAYOUT_ergodox(KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_RIGHT, KC_TAB, KC_KP_SLASH, KC_KP_ASTERISK, KC_KP_MINUS, KC_TRNS, KC_TRNS, KC_UP, KC_7, KC_8, KC_9, KC_KP_PLUS, KC_TRNS, KC_DOWN, KC_4, KC_5, KC_6, KC_PLUS, KC_TRNS, KC_TRNS, KC_LEFT, KC_1, KC_2, KC_3, KC_BSPC, KC_TRNS, KC_0, KC_DOT, KC_COMM, KC_NO, KC_NO, KC_TRNS, TG(1), KC_TRNS, KC_TRNS, KC_ENTER, KC_SPACE),
	[2] = LAYOUT_ergodox(KC_F12, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_TRNS, KC_TRNS, KC_1, KC_2, KC_3, KC_4, KC_5, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_TRNS, MO(4), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_BSPC, KC_TRNS, KC_TRNS, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_TRNS, KC_6, KC_7, KC_8, KC_9, KC_0, KC_TRNS, KC_NO, KC_MINS, KC_EQL, KC_LBRC, KC_RBRC, KC_BSLS, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, MO(2), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
	[3] = LAYOUT_ergodox(KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_NO, KC_AUDIO_VOL_UP, KC_NO, KC_NO, KC_NO, TG(5), KC_TRNS, KC_MEDIA_PREV_TRACK, KC_AUDIO_MUTE, KC_MEDIA_PLAY_PAUSE, KC_MEDIA_NEXT_TRACK, KC_NO, KC_TRNS, KC_NO, KC_AUDIO_VOL_DOWN, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_TRNS, MO(3), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_LEFT, KC_DOWN, KC_UP, KC_RIGHT, KC_NO, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, MO(4), KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
};

// Defining layer names: 
#define _MAIN   0
#define _NUMPAD 1

layer_state_t layer_state_set_user(layer_state_t state) {
  switch (biton32(state)) {
    case _MAIN:
      ergodox_right_led_1_off();
      ergodox_right_led_2_off();
      break;
    case _NUMPAD:
      ergodox_right_led_1_on();
      ergodox_right_led_2_off();
      break;
  }
  return state;
}